name: Generate Doc

on:
  push:
    branches:
      - master
    
jobs:
  generate_docs:
    name: Generate Swift Doc

    runs-on: macos-10.15
    
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      
      - name: Install swift_doc
        run: brew install swiftdocorg/formulae/swift-doc

      - name: Verify swift_doc
        run: swift-doc --version

      - name: Run swift_doc
        run: sh Scripts/docs.sh
        
