name: Test PR

on:
  pull_request:
    branches:
      - master
defaults:
  run:
    working-directory: ./Sample
    
jobs:
  test:
    name: Build and Test

    # See available software: https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md
    runs-on: macos-11

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
      - name: Prepare Xcode
        run: |
          sudo xcode-select --switch /Applications/Xcode_12.5.1.app
          xcodebuild -version
          swift --version
          xcrun simctl list devices 14.5

      - name: Boot simulator
        run: xcrun simctl boot "iPhone 12 Pro"

      - name: Run Internal tests
        run: xcodebuild clean build test -project Sample.xcodeproj -scheme "Sample-Internal" -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=14.5"

      - name: Run Production tests
        run: xcodebuild clean build test -project Sample.xcodeproj -scheme "Sample-Production" -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=14.5"

      - name: Build Internal tests iOS 12
        run: xcodebuild clean build -project Sample.xcodeproj -scheme "Sample-Internal" -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=12.4"

      - name: Run Production tests iOS 12
        run: xcodebuild clean build -project Sample.xcodeproj -scheme "Sample-Production" -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=12.4"
