name: Test PR

on:
  pull_request:
    branches:
      - master
    
jobs:
  test:
    name: Build and Test

    # See available software: https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md
    runs-on: macos-10.15

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
      - name: Prepare Xcode
        run: |
          sudo xcode-select --switch /Applications/Xcode_12.4.app
          xcodebuild -version
          swift --version
          xcrun simctl list devices 14.4

      - name: Boot simulator
        run: xcrun simctl boot "iPhone 12 Pro"

      - name: Run Internal tests
        run: xcodebuild clean build test -workspace Scenarios.xcworkspace -scheme "Sample-Internal" -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=14.4"

      - name: Run Production tests
        run: xcodebuild clean build test -workspace Scenarios.xcworkspace -scheme "Sample-Production" -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=14.4"
