name: Test PR

on:
  pull_request:
    branches:
      - master
    
jobs:
  test:
    name: Build and Test

    # See available software: https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md
    runs-on: macos-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      # - name: Prepare Xcode
      #   run: |
      #     sudo xcode-select --switch /Applications/Xcode_13.4.1.app
      #     xcodebuild -version
      #     swift --version
      #     xcrun simctl list devices 15.4

      - name: Boot simulator
        run: xcrun simctl boot "iPhone 15 Pro"

      - name: Run Internal tests
        run: xcodebuild clean build test -workspace Scenarios.xcworkspace -scheme "Sample-Internal" -destination "platform=iOS Simulator,name=iPhone 13 Pro,OS=latest"

      - name: Run Production tests
        run: xcodebuild clean build test -workspace Scenarios.xcworkspace -scheme "Sample-Production" -destination "platform=iOS Simulator,name=iPhone 13 Pro,OS=latest"

      - name: Run Internal (SwiftUI) tests
        run: xcodebuild clean build test -workspace Scenarios.xcworkspace -scheme "Sample-Internal" -destination "platform=iOS Simulator,name=iPhone 13 Pro,OS=latest"

      - name: Run Production (SwiftUI) tests
        run: xcodebuild clean build test -workspace Scenarios.xcworkspace -scheme "Sample-Production" -destination "platform=iOS Simulator,name=iPhone 13 Pro,OS=latest"
