name: Test PR on iOS 11

on:
  pull_request:
    branches:
      - master
    
jobs:
  test:
    name: Build and Test

    # See available software: https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md
    runs-on: macos-10.15

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Prepare Xcode
        run: |  
          ls -n /Applications/ | grep Xcode*
          sudo xcode-select --switch /Applications/Xcode_10.3.app
          xcodebuild -version
          swift --version
          xcrun simctl list devices 12.4

      - name: Boot simulator
        run: xcrun simctl boot "iPhone 5s"

      - name: Info
        run: |
          pwd
          xcodebuild -list

      - name: Build Internal tests iOS 12
        run: |
          xcodebuild clean build -workspace Scenarios.xcworkspace -scheme "Sample-Internal-iOS11" -destination "platform=iOS Simulator,name=iPhone 5s,OS=12.4"

