name: Test PR

on:
  pull_request:
    branches:
      - master
    
jobs:
  test:
    name: Build and Test

    # See available software: https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md
    runs-on: macos-11

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
      - name: Prepare Xcode
        run: |
          sudo xcode-select --switch /Applications/Xcode_13.2.app
          xcodebuild -version
          swift --version
          xcrun simctl list devices 15.2

      - name: Boot simulator
        run: xcrun simctl boot "iPhone 13 Pro"

      - name: Run Internal tests
        run: xcodebuild clean build test -workspace Scenarios.xcworkspace -scheme "Sample-Internal" -destination "platform=iOS Simulator,name=iPhone 13 Pro,OS=15.2"

      - name: Run Production tests
        run: xcodebuild clean build test -workspace Scenarios.xcworkspace -scheme "Sample-Production" -destination "platform=iOS Simulator,name=iPhone 13 Pro,OS=15.2"

      - name: Run Internal (SwiftUI) tests
        run: xcodebuild clean build test -workspace Scenarios.xcworkspace -scheme "Sample-Internal" -destination "platform=iOS Simulator,name=iPhone 13 Pro,OS=15.2"

      - name: Run Production (SwiftUI) tests
        run: xcodebuild clean build test -workspace Scenarios.xcworkspace -scheme "Sample-Production" -destination "platform=iOS Simulator,name=iPhone 13 Pro,OS=15.2"
